//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: device.proto
namespace device
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_get_device_list")]
  public partial class c2s_get_device_list : global::ProtoBuf.IExtensible
  {
    public c2s_get_device_list() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_get_device_list")]
  public partial class s2c_get_device_list : global::ProtoBuf.IExtensible
  {
    public s2c_get_device_list() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _reason = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private readonly global::System.Collections.Generic.List<device_info> _device_list = new global::System.Collections.Generic.List<device_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"device_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<device_info> device_list
    {
      get { return _device_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_select_device")]
  public partial class c2s_select_device : global::ProtoBuf.IExtensible
  {
    public c2s_select_device() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_select_device")]
  public partial class s2c_select_device : global::ProtoBuf.IExtensible
  {
    public s2c_select_device() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _reason = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private device_info _selected_device_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"selected_device_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public device_info selected_device_info
    {
      get { return _selected_device_info; }
      set { _selected_device_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"device_info")]
  public partial class device_info : global::ProtoBuf.IExtensible
  {
    public device_info() {}
    
    private int _device_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _device_ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"device_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_ip
    {
      get { return _device_ip; }
      set { _device_ip = value; }
    }
    private string _device_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"device_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_name
    {
      get { return _device_name; }
      set { _device_name = value; }
    }
    private string _road = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"road", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string road
    {
      get { return _road; }
      set { _road = value; }
    }
    private int _battary = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battary", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battary
    {
      get { return _battary; }
      set { _battary = value; }
    }
    private readonly global::System.Collections.Generic.List<video_info> _video_list = new global::System.Collections.Generic.List<video_info>();
    [global::ProtoBuf.ProtoMember(6, Name=@"video_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<video_info> video_list
    {
      get { return _video_list; }
    }
  
    private string _key = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"video_info")]
  public partial class video_info : global::ProtoBuf.IExtensible
  {
    public video_info() {}
    
    private string _url = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}