//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_login")]
  public partial class c2s_login : global::ProtoBuf.IExtensible
  {
    public c2s_login() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _userpassword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userpassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userpassword
    {
      get { return _userpassword; }
      set { _userpassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_login")]
  public partial class s2c_login : global::ProtoBuf.IExtensible
  {
    public s2c_login() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _reason = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private readonly global::System.Collections.Generic.List<device_info> _device_list = new global::System.Collections.Generic.List<device_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"device_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<device_info> device_list
    {
      get { return _device_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"device_info")]
  public partial class device_info : global::ProtoBuf.IExtensible
  {
    public device_info() {}
    
    private int _device_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _device_ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"device_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_ip
    {
      get { return _device_ip; }
      set { _device_ip = value; }
    }
    private string _device_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"device_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_name
    {
      get { return _device_name; }
      set { _device_name = value; }
    }
    private string _road = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"road", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string road
    {
      get { return _road; }
      set { _road = value; }
    }
    private int _battary = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battary", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battary
    {
      get { return _battary; }
      set { _battary = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}