// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface c2s_loginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string username = 1;
    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string userpassword = 2;
    /**
     * <code>optional string userpassword = 2;</code>
     */
    boolean hasUserpassword();
    /**
     * <code>optional string userpassword = 2;</code>
     */
    java.lang.String getUserpassword();
    /**
     * <code>optional string userpassword = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserpasswordBytes();
  }
  /**
   * Protobuf type {@code c2s_login}
   */
  public static final class c2s_login extends
      com.google.protobuf.GeneratedMessage
      implements c2s_loginOrBuilder {
    // Use c2s_login.newBuilder() to construct.
    private c2s_login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private c2s_login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final c2s_login defaultInstance;
    public static c2s_login getDefaultInstance() {
      return defaultInstance;
    }

    public c2s_login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private c2s_login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userpassword_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_c2s_login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_c2s_login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.c2s_login.class, Login.c2s_login.Builder.class);
    }

    public static com.google.protobuf.Parser<c2s_login> PARSER =
        new com.google.protobuf.AbstractParser<c2s_login>() {
      public c2s_login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new c2s_login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<c2s_login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userpassword = 2;
    public static final int USERPASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object userpassword_;
    /**
     * <code>optional string userpassword = 2;</code>
     */
    public boolean hasUserpassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userpassword = 2;</code>
     */
    public java.lang.String getUserpassword() {
      java.lang.Object ref = userpassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userpassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userpassword = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserpasswordBytes() {
      java.lang.Object ref = userpassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userpassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      username_ = "";
      userpassword_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserpasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserpasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Login.c2s_login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.c2s_login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.c2s_login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.c2s_login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.c2s_login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.c2s_login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Login.c2s_login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Login.c2s_login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Login.c2s_login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.c2s_login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Login.c2s_login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code c2s_login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Login.c2s_loginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_c2s_login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_c2s_login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.c2s_login.class, Login.c2s_login.Builder.class);
      }

      // Construct using Login.c2s_login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userpassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_c2s_login_descriptor;
      }

      public Login.c2s_login getDefaultInstanceForType() {
        return Login.c2s_login.getDefaultInstance();
      }

      public Login.c2s_login build() {
        Login.c2s_login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Login.c2s_login buildPartial() {
        Login.c2s_login result = new Login.c2s_login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userpassword_ = userpassword_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login.c2s_login) {
          return mergeFrom((Login.c2s_login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login.c2s_login other) {
        if (other == Login.c2s_login.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasUserpassword()) {
          bitField0_ |= 0x00000002;
          userpassword_ = other.userpassword_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login.c2s_login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login.c2s_login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // optional string userpassword = 2;
      private java.lang.Object userpassword_ = "";
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public boolean hasUserpassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public java.lang.String getUserpassword() {
        java.lang.Object ref = userpassword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userpassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserpasswordBytes() {
        java.lang.Object ref = userpassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userpassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public Builder setUserpassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userpassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public Builder clearUserpassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userpassword_ = getDefaultInstance().getUserpassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userpassword = 2;</code>
       */
      public Builder setUserpasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userpassword_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:c2s_login)
    }

    static {
      defaultInstance = new c2s_login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:c2s_login)
  }

  public interface s2c_loginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1;
    /**
     * <code>optional int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1;</code>
     */
    int getResult();

    // optional int32 reason = 2;
    /**
     * <code>optional int32 reason = 2;</code>
     */
    boolean hasReason();
    /**
     * <code>optional int32 reason = 2;</code>
     */
    int getReason();

    // repeated .device_info device_list = 3;
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    java.util.List<Login.device_info> 
        getDeviceListList();
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    Login.device_info getDeviceList(int index);
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    int getDeviceListCount();
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    java.util.List<? extends Login.device_infoOrBuilder> 
        getDeviceListOrBuilderList();
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    Login.device_infoOrBuilder getDeviceListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code s2c_login}
   */
  public static final class s2c_login extends
      com.google.protobuf.GeneratedMessage
      implements s2c_loginOrBuilder {
    // Use s2c_login.newBuilder() to construct.
    private s2c_login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private s2c_login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final s2c_login defaultInstance;
    public static s2c_login getDefaultInstance() {
      return defaultInstance;
    }

    public s2c_login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private s2c_login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reason_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                deviceList_ = new java.util.ArrayList<Login.device_info>();
                mutable_bitField0_ |= 0x00000004;
              }
              deviceList_.add(input.readMessage(Login.device_info.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          deviceList_ = java.util.Collections.unmodifiableList(deviceList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_s2c_login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_s2c_login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.s2c_login.class, Login.s2c_login.Builder.class);
    }

    public static com.google.protobuf.Parser<s2c_login> PARSER =
        new com.google.protobuf.AbstractParser<s2c_login>() {
      public s2c_login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new s2c_login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<s2c_login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    // optional int32 reason = 2;
    public static final int REASON_FIELD_NUMBER = 2;
    private int reason_;
    /**
     * <code>optional int32 reason = 2;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 reason = 2;</code>
     */
    public int getReason() {
      return reason_;
    }

    // repeated .device_info device_list = 3;
    public static final int DEVICE_LIST_FIELD_NUMBER = 3;
    private java.util.List<Login.device_info> deviceList_;
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    public java.util.List<Login.device_info> getDeviceListList() {
      return deviceList_;
    }
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    public java.util.List<? extends Login.device_infoOrBuilder> 
        getDeviceListOrBuilderList() {
      return deviceList_;
    }
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    public int getDeviceListCount() {
      return deviceList_.size();
    }
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    public Login.device_info getDeviceList(int index) {
      return deviceList_.get(index);
    }
    /**
     * <code>repeated .device_info device_list = 3;</code>
     */
    public Login.device_infoOrBuilder getDeviceListOrBuilder(
        int index) {
      return deviceList_.get(index);
    }

    private void initFields() {
      result_ = 0;
      reason_ = 0;
      deviceList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, reason_);
      }
      for (int i = 0; i < deviceList_.size(); i++) {
        output.writeMessage(3, deviceList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reason_);
      }
      for (int i = 0; i < deviceList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, deviceList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Login.s2c_login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.s2c_login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.s2c_login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.s2c_login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.s2c_login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.s2c_login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Login.s2c_login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Login.s2c_login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Login.s2c_login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.s2c_login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Login.s2c_login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code s2c_login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Login.s2c_loginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_s2c_login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_s2c_login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.s2c_login.class, Login.s2c_login.Builder.class);
      }

      // Construct using Login.s2c_login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (deviceListBuilder_ == null) {
          deviceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          deviceListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_s2c_login_descriptor;
      }

      public Login.s2c_login getDefaultInstanceForType() {
        return Login.s2c_login.getDefaultInstance();
      }

      public Login.s2c_login build() {
        Login.s2c_login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Login.s2c_login buildPartial() {
        Login.s2c_login result = new Login.s2c_login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reason_ = reason_;
        if (deviceListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            deviceList_ = java.util.Collections.unmodifiableList(deviceList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.deviceList_ = deviceList_;
        } else {
          result.deviceList_ = deviceListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login.s2c_login) {
          return mergeFrom((Login.s2c_login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login.s2c_login other) {
        if (other == Login.s2c_login.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        if (deviceListBuilder_ == null) {
          if (!other.deviceList_.isEmpty()) {
            if (deviceList_.isEmpty()) {
              deviceList_ = other.deviceList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDeviceListIsMutable();
              deviceList_.addAll(other.deviceList_);
            }
            onChanged();
          }
        } else {
          if (!other.deviceList_.isEmpty()) {
            if (deviceListBuilder_.isEmpty()) {
              deviceListBuilder_.dispose();
              deviceListBuilder_ = null;
              deviceList_ = other.deviceList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              deviceListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDeviceListFieldBuilder() : null;
            } else {
              deviceListBuilder_.addAllMessages(other.deviceList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login.s2c_login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login.s2c_login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1;
      private int result_ ;
      /**
       * <code>optional int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional int32 reason = 2;
      private int reason_ ;
      /**
       * <code>optional int32 reason = 2;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 reason = 2;</code>
       */
      public int getReason() {
        return reason_;
      }
      /**
       * <code>optional int32 reason = 2;</code>
       */
      public Builder setReason(int value) {
        bitField0_ |= 0x00000002;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reason = 2;</code>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reason_ = 0;
        onChanged();
        return this;
      }

      // repeated .device_info device_list = 3;
      private java.util.List<Login.device_info> deviceList_ =
        java.util.Collections.emptyList();
      private void ensureDeviceListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          deviceList_ = new java.util.ArrayList<Login.device_info>(deviceList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Login.device_info, Login.device_info.Builder, Login.device_infoOrBuilder> deviceListBuilder_;

      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public java.util.List<Login.device_info> getDeviceListList() {
        if (deviceListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(deviceList_);
        } else {
          return deviceListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public int getDeviceListCount() {
        if (deviceListBuilder_ == null) {
          return deviceList_.size();
        } else {
          return deviceListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Login.device_info getDeviceList(int index) {
        if (deviceListBuilder_ == null) {
          return deviceList_.get(index);
        } else {
          return deviceListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder setDeviceList(
          int index, Login.device_info value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.set(index, value);
          onChanged();
        } else {
          deviceListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder setDeviceList(
          int index, Login.device_info.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.set(index, builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder addDeviceList(Login.device_info value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.add(value);
          onChanged();
        } else {
          deviceListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder addDeviceList(
          int index, Login.device_info value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.add(index, value);
          onChanged();
        } else {
          deviceListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder addDeviceList(
          Login.device_info.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.add(builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder addDeviceList(
          int index, Login.device_info.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.add(index, builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder addAllDeviceList(
          java.lang.Iterable<? extends Login.device_info> values) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          super.addAll(values, deviceList_);
          onChanged();
        } else {
          deviceListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder clearDeviceList() {
        if (deviceListBuilder_ == null) {
          deviceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          deviceListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Builder removeDeviceList(int index) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.remove(index);
          onChanged();
        } else {
          deviceListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Login.device_info.Builder getDeviceListBuilder(
          int index) {
        return getDeviceListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Login.device_infoOrBuilder getDeviceListOrBuilder(
          int index) {
        if (deviceListBuilder_ == null) {
          return deviceList_.get(index);  } else {
          return deviceListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public java.util.List<? extends Login.device_infoOrBuilder> 
           getDeviceListOrBuilderList() {
        if (deviceListBuilder_ != null) {
          return deviceListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(deviceList_);
        }
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Login.device_info.Builder addDeviceListBuilder() {
        return getDeviceListFieldBuilder().addBuilder(
            Login.device_info.getDefaultInstance());
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public Login.device_info.Builder addDeviceListBuilder(
          int index) {
        return getDeviceListFieldBuilder().addBuilder(
            index, Login.device_info.getDefaultInstance());
      }
      /**
       * <code>repeated .device_info device_list = 3;</code>
       */
      public java.util.List<Login.device_info.Builder> 
           getDeviceListBuilderList() {
        return getDeviceListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Login.device_info, Login.device_info.Builder, Login.device_infoOrBuilder> 
          getDeviceListFieldBuilder() {
        if (deviceListBuilder_ == null) {
          deviceListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Login.device_info, Login.device_info.Builder, Login.device_infoOrBuilder>(
                  deviceList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          deviceList_ = null;
        }
        return deviceListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:s2c_login)
    }

    static {
      defaultInstance = new s2c_login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:s2c_login)
  }

  public interface device_infoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 device_id = 1;
    /**
     * <code>optional int32 device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional int32 device_id = 1;</code>
     */
    int getDeviceId();

    // optional string device_ip = 2;
    /**
     * <code>optional string device_ip = 2;</code>
     */
    boolean hasDeviceIp();
    /**
     * <code>optional string device_ip = 2;</code>
     */
    java.lang.String getDeviceIp();
    /**
     * <code>optional string device_ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIpBytes();

    // optional string device_name = 3;
    /**
     * <code>optional string device_name = 3;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>optional string device_name = 3;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>optional string device_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    // optional string road = 4;
    /**
     * <code>optional string road = 4;</code>
     */
    boolean hasRoad();
    /**
     * <code>optional string road = 4;</code>
     */
    java.lang.String getRoad();
    /**
     * <code>optional string road = 4;</code>
     */
    com.google.protobuf.ByteString
        getRoadBytes();

    // optional int32 battary = 5;
    /**
     * <code>optional int32 battary = 5;</code>
     */
    boolean hasBattary();
    /**
     * <code>optional int32 battary = 5;</code>
     */
    int getBattary();
  }
  /**
   * Protobuf type {@code device_info}
   */
  public static final class device_info extends
      com.google.protobuf.GeneratedMessage
      implements device_infoOrBuilder {
    // Use device_info.newBuilder() to construct.
    private device_info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private device_info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final device_info defaultInstance;
    public static device_info getDefaultInstance() {
      return defaultInstance;
    }

    public device_info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private device_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceIp_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              deviceName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              road_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              battary_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_device_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_device_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.device_info.class, Login.device_info.Builder.class);
    }

    public static com.google.protobuf.Parser<device_info> PARSER =
        new com.google.protobuf.AbstractParser<device_info>() {
      public device_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new device_info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<device_info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private int deviceId_;
    /**
     * <code>optional int32 device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 device_id = 1;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }

    // optional string device_ip = 2;
    public static final int DEVICE_IP_FIELD_NUMBER = 2;
    private java.lang.Object deviceIp_;
    /**
     * <code>optional string device_ip = 2;</code>
     */
    public boolean hasDeviceIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string device_ip = 2;</code>
     */
    public java.lang.String getDeviceIp() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string device_name = 3;
    public static final int DEVICE_NAME_FIELD_NUMBER = 3;
    private java.lang.Object deviceName_;
    /**
     * <code>optional string device_name = 3;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string device_name = 3;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string road = 4;
    public static final int ROAD_FIELD_NUMBER = 4;
    private java.lang.Object road_;
    /**
     * <code>optional string road = 4;</code>
     */
    public boolean hasRoad() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string road = 4;</code>
     */
    public java.lang.String getRoad() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          road_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string road = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRoadBytes() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        road_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 battary = 5;
    public static final int BATTARY_FIELD_NUMBER = 5;
    private int battary_;
    /**
     * <code>optional int32 battary = 5;</code>
     */
    public boolean hasBattary() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 battary = 5;</code>
     */
    public int getBattary() {
      return battary_;
    }

    private void initFields() {
      deviceId_ = 0;
      deviceIp_ = "";
      deviceName_ = "";
      road_ = "";
      battary_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRoadBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, battary_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRoadBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, battary_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Login.device_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.device_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.device_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login.device_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login.device_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.device_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Login.device_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Login.device_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Login.device_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Login.device_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Login.device_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Login.device_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_device_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_device_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.device_info.class, Login.device_info.Builder.class);
      }

      // Construct using Login.device_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        road_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        battary_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_device_info_descriptor;
      }

      public Login.device_info getDefaultInstanceForType() {
        return Login.device_info.getDefaultInstance();
      }

      public Login.device_info build() {
        Login.device_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Login.device_info buildPartial() {
        Login.device_info result = new Login.device_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceIp_ = deviceIp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.road_ = road_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.battary_ = battary_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login.device_info) {
          return mergeFrom((Login.device_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login.device_info other) {
        if (other == Login.device_info.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasDeviceIp()) {
          bitField0_ |= 0x00000002;
          deviceIp_ = other.deviceIp_;
          onChanged();
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000004;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasRoad()) {
          bitField0_ |= 0x00000008;
          road_ = other.road_;
          onChanged();
        }
        if (other.hasBattary()) {
          setBattary(other.getBattary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login.device_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login.device_info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 device_id = 1;
      private int deviceId_ ;
      /**
       * <code>optional int32 device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 device_id = 1;</code>
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>optional int32 device_id = 1;</code>
       */
      public Builder setDeviceId(int value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0;
        onChanged();
        return this;
      }

      // optional string device_ip = 2;
      private java.lang.Object deviceIp_ = "";
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public boolean hasDeviceIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public java.lang.String getDeviceIp() {
        java.lang.Object ref = deviceIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIpBytes() {
        java.lang.Object ref = deviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public Builder setDeviceIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public Builder clearDeviceIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceIp_ = getDefaultInstance().getDeviceIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_ip = 2;</code>
       */
      public Builder setDeviceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceIp_ = value;
        onChanged();
        return this;
      }

      // optional string device_name = 3;
      private java.lang.Object deviceName_ = "";
      /**
       * <code>optional string device_name = 3;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string device_name = 3;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_name = 3;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 3;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 3;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceName_ = value;
        onChanged();
        return this;
      }

      // optional string road = 4;
      private java.lang.Object road_ = "";
      /**
       * <code>optional string road = 4;</code>
       */
      public boolean hasRoad() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string road = 4;</code>
       */
      public java.lang.String getRoad() {
        java.lang.Object ref = road_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          road_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string road = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRoadBytes() {
        java.lang.Object ref = road_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          road_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string road = 4;</code>
       */
      public Builder setRoad(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        road_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string road = 4;</code>
       */
      public Builder clearRoad() {
        bitField0_ = (bitField0_ & ~0x00000008);
        road_ = getDefaultInstance().getRoad();
        onChanged();
        return this;
      }
      /**
       * <code>optional string road = 4;</code>
       */
      public Builder setRoadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        road_ = value;
        onChanged();
        return this;
      }

      // optional int32 battary = 5;
      private int battary_ ;
      /**
       * <code>optional int32 battary = 5;</code>
       */
      public boolean hasBattary() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 battary = 5;</code>
       */
      public int getBattary() {
        return battary_;
      }
      /**
       * <code>optional int32 battary = 5;</code>
       */
      public Builder setBattary(int value) {
        bitField0_ |= 0x00000010;
        battary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 battary = 5;</code>
       */
      public Builder clearBattary() {
        bitField0_ = (bitField0_ & ~0x00000010);
        battary_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:device_info)
    }

    static {
      defaultInstance = new device_info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:device_info)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_c2s_login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_c2s_login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_s2c_login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_s2c_login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_device_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_device_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\"3\n\tc2s_login\022\020\n\010username\030\001" +
      " \001(\t\022\024\n\014userpassword\030\002 \001(\t\"N\n\ts2c_login\022" +
      "\016\n\006result\030\001 \001(\005\022\016\n\006reason\030\002 \001(\005\022!\n\013devic" +
      "e_list\030\003 \003(\0132\014.device_info\"g\n\013device_inf" +
      "o\022\021\n\tdevice_id\030\001 \001(\005\022\021\n\tdevice_ip\030\002 \001(\t\022" +
      "\023\n\013device_name\030\003 \001(\t\022\014\n\004road\030\004 \001(\t\022\017\n\007ba" +
      "ttary\030\005 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_c2s_login_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_c2s_login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_c2s_login_descriptor,
              new java.lang.String[] { "Username", "Userpassword", });
          internal_static_s2c_login_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_s2c_login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_s2c_login_descriptor,
              new java.lang.String[] { "Result", "Reason", "DeviceList", });
          internal_static_device_info_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_device_info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_device_info_descriptor,
              new java.lang.String[] { "DeviceId", "DeviceIp", "DeviceName", "Road", "Battary", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
